# Generated by Django 4.0.4 on 2022-05-23 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.date(2022, 5, 23)),
        ),
    ]
