# Generated by Django 4.0.4 on 2022-05-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(null=True),
        ),
    ]
