# Generated by Django 4.0.4 on 2022-05-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_date',
        ),
    ]
