# Generated by Django 4.0.4 on 2022-05-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadtime',
            field=models.CharField(max_length=50, null=True, verbose_name='DeadTime'),
        ),
    ]
